version: 2

updates:
  - package-ecosystem: maven
    directory: /
    target-branch: next
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore(deps)
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    target-branch: next
    commit-message:
      prefix: ci(deps)
    schedule:
      interval: daily
